language: java
jdk:
- oraclejdk8
install: true
addons:
  apt:
    packages:
    - rpm
script: mvn -q -T2 clean test
after_success:
- bash <(curl -s https://codecov.io/bash)
- cp build/conditionalbuild.sh /tmp/
- chmod a+x /tmp/conditionalbuild.sh
- /tmp/conditionalbuild.sh
env:
  global:
  - REPO=git@github.com:srotya/kafka-lag-monitor.git
cache:
  directories:
  - $HOME/.m2
